#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

colorflag="--color"

# List all files colorized in long format
alias ll="ls -lah $colorflag --group-directories-first"

# List only directories
alias lsd="ls -lF $colorflag | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls $colorflag"

# Always enable colored `grep` output
alias grep='grep --color=auto '

# Always enable colored `fgrep` output (grep -F)
alias fgrep='fgrep --color=auto'

# Always enable colored `egrep` output (grep -E)
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Untar
alias untar='tar xvf'

# Tar
alias targz='tar -czvf'

# Usage: be rails data:migrate && rdy
alias rdy='notify-send "Task is done"'

# Kill process in port 3000
alias kill3000="fuser -k -n tcp 3000"

# Kill redis
alias killredis="fuser -k -n tcp 6379"

# Kill process at given port
alias killport="fuser -k -n tcp $1"

# Run emacs in terminal mode
alias emacs="emacs -nw"

# nvim config
alias vimrc="nvim ~/.config/nvim/init.vim"

# Alias vim into nvim
alias vim="nvim"

# Zsh config
alias zshconfig="vim ~/.zshrc"

# Ohmyzsh config
alias ohmyzsh="vim ~/.oh-my-zsh"

# Cd into scripts dir
alias scripts="cd ~/scripts"

# Rails
alias be="bundle exec"

# Toy weather script :P
alias wtr="cd ~/scripts && wtr && cd ~"

# Lua wont run
alias lua="/home/vicentesantos/Downloads/lua-5.3.3/src/lua"
